name: Build java 1.8 project
on:
  push:
    branches: [ master ]
  pull_request: [ master ]
jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    -name: Set up JDK 1.8
     uses: actions/setup-java@v1
     with:
       java-version: 1.8

    -name: Grant execute permission for graddlew
     run: chmod +x gradlew
    
    -name: Build with gradle
     run: ./gradlew build   

